services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    networks:
      - proxy_net

networks:
  proxy_net:
    driver: bridge
