services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    restart: "on-failure"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=techfixsolutions_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=dev1234
      - POSTGRES_HOST=db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: techfixsolutions_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dev1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
